name: Pylint

on: [push]

jobs:
  build:
    runs-on: debian-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python v${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run lint
      run: |
        pylint mysql2click.py
